import { TABLES_ENUM } from "../constants/enums";
import { TableColumn } from "../types/database";
export type UserSchema = {
  id: number;
  public_id: string;
  name?: string | null;
  surname?: string | null;
  username: string;
  password: string;
  stripe_customer_id?: string | null;
  profession?: string | null;
  biography?: string | null;
  email: string;
  avatar?: string;
  banner?: string;
  email_validated?: boolean;
  is_active?: boolean;
  funnel_step: number;
  short_biography?: string;
  number_email_validations_sent?: number;
  twofa_enabled?: boolean;
  twofa_code?: string;
  twofa_expires_at?: Date;
  twofa_attempts?: number;
  created_at: Date;
  updated_at: Date;
};
export type UserSchemaWithoutTimestamps = Omit<UserSchema, 'created_at' | 'updated_at'>;
export type BaseUserSchema = Omit<UserSchema, 'created_at' | 'updated_at'  | 'name'| 'surname'| 'biography' |'avatar' |'banner'>;
const tablesUser = [TABLES_ENUM.USERS] as const;
export type UserSchemaColumns = TableColumn<typeof tablesUser, UserSchemaWithoutTimestamps>;
export type BaseUserSchemaColumns = TableColumn<typeof tablesUser, BaseUserSchema>;

