import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/shadcn/sonner"
import { SessionProvider } from "@/modules/auth/contexts/session.provider";
import { ReactElement } from "react";
import { Roboto } from 'next/font/google'
import { cn } from "@repo/ui/lib/utils";
 
const roboto = Roboto({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactElement;
}>) {
  return (
    <html className={cn("dark",roboto.className)} lang="en">
      <body className=" w-screen h-screen">
        <SessionProvider>
          {children}
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
