import { userSession } from "@/modules/auth/server-actions/user-session.action";
import type { Metadata } from "next";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAuth = await userSession();
  if (userAuth) {
    redirect('/atelier');
  }

  return (
    <main className="min-h-screen flex flex-col">
      <header>

        <nav>atelier</nav>
      </header>
      {children}
    </main>
  );
}
