import { userSession } from "@/modules/auth/server-actions/user-session.action";
import type { Metadata } from "next";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAuth = await userSession();
  if (userAuth) {
    redirect('/atelier');
  }

  return (
    <>
      <header className=" border-white border w-full py-6">
        <nav>atelier</nav>
      </header>
      <main className="h-full w-full">
        {children}
      </main>

    </>
  );
}
