import { config } from "@/lib/config";
import { userSession } from "@/modules/auth/server-actions/user-session.action";
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userAuth = await userSession();
  if (userAuth) {
    redirect('/atelier');
  }

  return (
    <>
      <header className="w-full py-6 flex items-center justify-center  shadow-sm shadow-fg-1 bg-fg">
        <nav className="flex items-center h-full justify-between px-8 w-full">
          <Link className="sm:text-lg text-base" href={'/'}>{config.app_name.toUpperCase()}</Link>
          <div>
            <Link href={'/auth/register'} className="bg-accent text-white text-xs sm:text-sm px-4 py-2 rounded-3xl ">Create an account</Link>
          </div>
        </nav>
      </header>
      <main className="size-full">
        {children}
      </main>

    </>
  );
}
