/**
 * API Error Codes for frontend error handling
 * Naming convention: CATEGORY_SUBCATEGORY_SPECIFIC
 */
export const API_ERRORS = {
  // USER LIMITS - Storage & Media
  USER_LIMITS_storage_used_mb_EXCEEDED: 'USER_LIMITS_storage_used_mb_EXCEEDED',
  USER_LIMITS_DAILY_STORAGE_REQUESTS_EXCEEDED: 'USER_LIMITS_DAILY_STORAGE_REQUESTS_EXCEEDED',
  USER_LIMITS_COMPRESSION_NOT_ALLOWED: 'USER_LIMITS_COMPRESSION_NOT_ALLOWED',

  // USER LIMITS - Entity Counts
  USER_LIMITS_MAX_PROJECTS_EXCEEDED: 'USER_LIMITS_MAX_PROJECTS_EXCEEDED',
  USER_LIMITS_MAX_PORTFOLIOS_EXCEEDED: 'USER_LIMITS_MAX_PORTFOLIOS_EXCEEDED',
  USER_LIMITS_MAX_PORTFOLIO_ITEMS_EXCEEDED: 'USER_LIMITS_MAX_PORTFOLIO_ITEMS_EXCEEDED',
  USER_LIMITS_MAX_CLIENTS_EXCEEDED: 'USER_LIMITS_MAX_CLIENTS_EXCEEDED',
  USER_LIMITS_MAX_SERVICES_EXCEEDED: 'USER_LIMITS_MAX_SERVICES_EXCEEDED',
  USER_LIMITS_MAX_HIGHLIGHTS_EXCEEDED: 'USER_LIMITS_MAX_HIGHLIGHTS_EXCEEDED',

  // USER LIMITS - AI & Credits
  USER_LIMITS_AI_CREDITS_EXCEEDED: 'USER_LIMITS_AI_CREDITS_EXCEEDED',

  // CONTENT MODERATION
  CONTENT_MODERATION_NOT_ALLOWED: 'CONTENT_MODERATION_NOT_ALLOWED',
  ACCOUNT_STRIKES_EXCEEDED: 'ACCOUNT_STRIKES_EXCEEDED',
} as const;

export type ApiErrorKey = keyof typeof API_ERRORS;