export const ENUMS = {
    PRODUCT_TYPE: ['PLAN'] as const,
    BILLING_TYPE: ['MONTHLY', 'QUARTERLY', 'YEARLY', 'LIFETIME'] as const,
    USER_EDITORS_ROLES: ['ADMIN', 'EDITOR'] as const,
    LANGUAGE_CODE: ['EN', 'ES', 'PT'] as const,
    MEDIA_TYPE: ['IMAGE', 'VIDEO'] as const,
    MEDIA_EXTENSION: ['JPG', 'JPEG', 'PNG', 'GIF', 'MP4', 'MOV'] as const,
    MEDIA_SHAPE: ['SQUARE', 'LANDSCAPE', 'PORTRAIT'] as const,
    PROJECT_STATUS: [
      'NOT_STARTED',
      'PENDING',
      'IN_PROGRESS',
      'COMPLETED',
      'CANCELLED',
      'PENDING_PAYMENT',
      'PAUSED',
    ] as const,
    PAYMENT_METHOD: ['CARD', 'PAYPAL'] as const,
    PLAN_OFFERS_TYPE: ['FREE', 'DISCOUNT'] as const,
    PASSWORD_RECOVERY_ATTEMPT_STATUS: ['CODE_NOT_VALIDATED','CODE_VALIDATED','PASSWORD_CHANGED'],
    STRIPE_ERROR: [
      'StripeCardError',
      'StripeInvalidRequestError',
      'StripeConnectionError',
      'StripeAPIError',
      'StripeAuthenticationError',
      'StripeIdempotencyError',
      'StripePermissionError',
      'StripeRateLimitError',
      'StripeSignatureVerificationError',
    ] as const,
    STRIPE_RAW_ERROR_TYPE: [
      'card_error',
      'invalid_request_error',
      'api_error',
      'idempotency_error',
      'rate_limit_error',
      'authentication_error',
      'invalid_grant',
      'temporary_session_expired',
    ] as const,
  };
// TABLES
export const TABLES_ENUM = {
  PLANS:'plans',
  PLAN_PRICES:'plan_prices',
  PLAN_TRANSLATIONS:'plan_translations',
  PLAN_OFFERS:'plan_offers',
  USER_EXTRA_DATA:'user_extra_data',
  ADMIN_USERS:'admin_users',
  ADMIN_USERS_ROLES:'admin_users_roles',
  USERS:'users',
  CATEGORIES:'categories',
  USER_CATEGORIES:'user_categories',
  CATEGORY_TRANSLATIONS:'category_translations',
  PLAN_SUBSCRIPTIONS: 'plan_subscriptions',
  TRANSACTIONS:'transactions',
  MIGRATIONS:'migrations',
  MEDIA:'media',
  MEDIA_TRANSLATIONS:'media_translations',
  COLLECTIONS:'collections',
  COLLECTION_MEDIA:'collection_media',
  COLLECTION_TRANSLATIONS:'collection_translations',
  PORTFOLIOS:'portfolios',
  PORTFOLIO_CATEGORIES:'portfolio_categories',
  PORTFOLIO_MEDIA:'portfolio_media',
  PORTFOLIO_COLLECTION:'portfolio_collection',
  PORTFOLIO_TRANSLATIONS:'portfolio_translations',
  PROJECTS:'projects',
  PROJECT_MEDIA:'project_media',
  PROJECT_TRANSLATIONS:'project_translations',
  CLIENTS:'clients',
  CLIENT_MEDIA:'client_media',
  CLIENT_TRANSLATIONS:'client_translations',
  SERVICES:'services',
  SERVICE_MEDIA:'service_media',
  SERVICE_TRANSLATIONS:'service_translations',
  ADDRESSES:'addresses',
  USER_AUTH_DEVICES:'user_auth_devices',
  USER_SESSIONS:'user_sessions',
  PASSWORD_RECOVERY_ATTEMPTS:'password_recovery_attempts',
} as const;

  export type AvailableEnums = keyof typeof ENUMS;
  export type EnumType<T extends AvailableEnums> = (typeof ENUMS)[T][number];
