import Logger from '@repo/backend-lib/utils/console';
import { killClient } from '../client';
import { Query } from '../facades';
import { connectDb } from './utils';

/**
 * Forces a fresh AI SEO generation for one artist on the next nightly sweep
 * (`findDueForSeoGeneration`), bypassing the regeneration throttle.
 *
 * Setting `seo_generated_at` to NULL takes the "never generated" branch of the sweep — the same
 * state a new profile is in. Use it when the stored copy is known to be wrong (e.g. it names a city
 * the artist no longer lives in); ordinary edits already mark SEO stale on their own.
 */
const requeueUserSeo = async (username: string) => {
  try {
    await connectDb();
    const result = (await Query.raw(
      `UPDATE users SET seo_generated_at = NULL WHERE username = $1 RETURNING id, username`,
      [username],
    )) as unknown;
    const r = result as { rows?: { id: number }[] } | { id: number }[][] | undefined;
    const rows = Array.isArray(r) ? r[0] : r?.rows ?? [];
    if (!rows?.length) {
      Logger.error(`❌ No user "${username}".`);
      process.exit(1);
    }
    Logger.success(`✅ @${username}: SEO will be regenerated by the next nightly run (00:00 UTC).`);
    process.exit(0);
  } catch (error) {
    Logger.error('❌ seo:requeue-user failed:', error);
    process.exit(1);
  } finally {
    await killClient();
  }
};

export { requeueUserSeo };
