import { databaseCliConfig } from './config';
import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { Query } from '../../facades';
import { DatabaseClient } from '@repo/common-lib/types/database';
import Logger from '@repo/backend-lib/utils/console';
import { initClient } from '../../client';
import {config} from '@repo/common-lib/config';
import {
  createUpdatedAtTrigger,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
} from './triggers';

// Migration files live as `.ts` in source (`src/migrations`) and are compiled to
// `.js` in `dist/src/migrations`. The production CLI always runs from dist, so the
// canonical identity stored in the `migrations` table is the `.js` name. Normalizing
// here keeps `migrate` and `rollback` in agreement no matter which extension happens
// to be on disk (or was recorded previously), so rollback never fails to locate a
// file just because the DB stored a `.ts` name.
const MIGRATION_EXTENSIONS = ['.js', '.ts'] as const;

const stripMigrationExtension = (name: string) =>
  name.replace(/\.(js|ts)$/i, '');

const normalizeMigrationName = (name: string) =>
  `${stripMigrationExtension(name)}.js`;

// Resolve the actual migration file on disk, tolerating either extension so the CLI
// works whether it is run from dist (`.js`) or against source (`.ts`).
const resolveMigrationPath = (directory: string, name: string): string | null => {
  const base = stripMigrationExtension(name);
  for (const ext of MIGRATION_EXTENSIONS) {
    const candidate = path.join(directory, `${base}${ext}`);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
};

const handleMigration = async (
  callback: (migration: any, migrationName: string) => Promise<void>,
  rollback: boolean = false,
) => {
  try {
    const migrationDirectory = databaseCliConfig.migrationsDirectory;
    if (!fs.existsSync(migrationDirectory)) {
      fs.mkdirSync(migrationDirectory, { recursive: true });
    }
    // If rollback is true, we need to get the migrations from the database order by the last created at
    let migrations = !rollback
      ? fs.readdirSync(migrationDirectory)
      : (
          await Query.table('migrations')
            .select('name')
            .orderBy('created_at', 'DESC')
            .get()
        ).map((migration: any) => migration.name);

    if (migrations.length === 0) {
      Logger.info(
        `No migrations ${!rollback ? '' : 'to rollback'} found`,
      );
      // Important: don't hard-exit from here. Callers (e.g. db:fresh with
      // exitProcess: false) should decide whether the process should continue.
      return;
    }

    // Sort migrations alphabetically by filename. Files generated by
    // `create-migration.ts` use a zero-padded `YYYY-MM-DD-HH-mm-ss-ms-<slug>.ts`
    // prefix, so lexicographic ordering matches chronological ordering. Files
    // that don't fully follow the convention are simply sorted alphabetically
    // (no error is thrown).
    if (!rollback) {
      migrations = migrations
        .filter(
          (file) =>
            (file.endsWith('.js') || file.endsWith('.ts')) &&
            !file.endsWith('.d.ts'),
        )
        .sort((a: string, b: string) => a.localeCompare(b));
    }

    for (const migration of migrations) {
      const migrationPath = resolveMigrationPath(migrationDirectory, migration);
      if (!migrationPath) {
        const expected = path.join(migrationDirectory, normalizeMigrationName(migration));
        Logger.error('❌ Migration file not found', expected);
        throw new Error(`Migration file not found: ${expected}`);
      }
      const migrationFile = await import(pathToFileURL(migrationPath).href);
      if (!migrationFile.up || !migrationFile.down) {
        Logger.error(
          '❌ Migration file is not valid, missing up or down function',
          migrationPath,
        );
        throw new Error(`Invalid migration file (missing up/down): ${migrationPath}`);
      }
      // Store/compare a canonical `.js` identity so the `migrations` table stays
      // consistent regardless of the on-disk extension used for this run.
      await callback(migrationFile, normalizeMigrationName(migration));
    }
  } catch (error) {
    Logger.error('❌ Migration failed:', error);
    throw error;
  }
};
const utilsPath = (fileName: string) => {
  return path.join(process.cwd(), 'src', 'lib', 'scripts', 'utils', fileName);
};
const connectDb = async () => {
  const dbConfig = config().database;
  await initClient({
    client: dbConfig.client as DatabaseClient,
    host: dbConfig.host,
    port: dbConfig.port,
    username: dbConfig.username,
    password: dbConfig.password,
    database: dbConfig.database,
    settings: databaseCliConfig,
  });
};
export {
  handleMigration,
  createUpdatedAtTrigger,
  connectDb,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
  utilsPath,
};
