import { databaseCliConfig } from './config';
import { templatesDirectory } from './paths';
import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { Query } from '../../facades';
import { DatabaseClient } from '@repo/common-lib/types/database';
import Logger from '@repo/backend-lib/utils/console';
import { initClient } from '../../client';
import {config} from '@repo/common-lib/config';
import {
  createUpdatedAtTrigger,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
} from './triggers';

// Migrations are authored as `.ts` in `src/migrations` and compiled to `.js` in
// `dist/src/migrations`. `migrate` / `rollback` only ever execute the compiled
// output, so the canonical identity stored in the `migrations` table is the `.js`
// name. Ledger rows written by older runs may still carry `.ts`; normalizing on
// read keeps those matched to their compiled file.
const stripMigrationExtension = (name: string) =>
  name.replace(/\.(js|ts)$/i, '');

const normalizeMigrationName = (name: string) =>
  `${stripMigrationExtension(name)}.js`;

/** Resolve a migration to its compiled file. `.js` only — never runs TypeScript. */
const resolveMigrationPath = (directory: string, name: string): string | null => {
  const candidate = path.join(directory, normalizeMigrationName(name));
  return fs.existsSync(candidate) ? candidate : null;
};

/**
 * A missing compiled directory means the package was never built (or dist was
 * cleaned). Creating it silently would turn that into a confusing "Nothing to
 * migrate", so fail loudly with the fix.
 */
const requireCompiledMigrationsDirectory = () => {
  const migrationDirectory = databaseCliConfig.migrationsDirectory;
  if (!fs.existsSync(migrationDirectory)) {
    Logger.error(
      '❌ Compiled migrations directory not found. Build the package first (`pnpm --filter @repo/database build`).',
      migrationDirectory,
    );
    throw new Error(
      `Compiled migrations directory not found: ${migrationDirectory}`,
    );
  }
  return migrationDirectory;
};

export type MigrationModule = {
  up: () => Promise<void>;
  down: () => Promise<void>;
};

/**
 * Loads the compiled migration on demand, or resolves to `null` when no `.js`
 * exists for it. Deliberately lazy: `rollback` reads its list from the ledger, so
 * a row whose file was deleted must not break iteration for every other row, and
 * a `--steps` budget must be able to stop before touching files it never needs.
 */
export type LoadMigration = () => Promise<MigrationModule | null>;

/** Returning `'stop'` ends iteration without loading any further migrations. */
export type MigrationHandler = (
  loadMigration: LoadMigration,
  migrationName: string,
) => Promise<void | 'stop'>;

const handleMigration = async (
  callback: MigrationHandler,
  rollback: boolean = false,
) => {
  try {
    const migrationDirectory = requireCompiledMigrationsDirectory();
    // If rollback is true, we need to get the migrations from the database order by the last created at
    let migrations: string[] = !rollback
      ? fs.readdirSync(migrationDirectory)
      : (
          await Query.table('migrations')
            .select('name')
            .orderBy('created_at', 'DESC')
            .get()
        ).map((migration: any) => migration.name);

    // Sort migrations alphabetically by filename. Files generated by
    // `create-migration.ts` use a zero-padded `YYYY-MM-DD-HH-mm-ss-ms-<slug>.ts`
    // prefix, so lexicographic ordering matches chronological ordering. Files
    // that don't fully follow the convention are simply sorted alphabetically
    // (no error is thrown).
    if (!rollback) {
      // `.js` only: `.d.ts`, `.d.ts.map`, `.js.map` and any stray `.ts` left in
      // dist by an older build are not migrations.
      migrations = migrations
        .filter((file) => file.endsWith('.js'))
        .sort((a, b) => a.localeCompare(b));
    }

    if (migrations.length === 0) {
      Logger.info(
        `No migrations ${!rollback ? '' : 'to rollback'} found`,
      );
      // Important: don't hard-exit from here. Callers (e.g. db:fresh with
      // exitProcess: false) should decide whether the process should continue.
      return;
    }

    for (const migration of migrations) {
      const loadMigration: LoadMigration = async () => {
        const migrationPath = resolveMigrationPath(migrationDirectory, migration);
        if (!migrationPath) return null;
        const migrationFile = await import(pathToFileURL(migrationPath).href);
        if (!migrationFile.up || !migrationFile.down) {
          Logger.error(
            '❌ Migration file is not valid, missing up or down function',
            migrationPath,
          );
          throw new Error(`Invalid migration file (missing up/down): ${migrationPath}`);
        }
        return migrationFile as MigrationModule;
      };
      // Store/compare a canonical `.js` identity so the `migrations` table stays
      // consistent with what is actually executed.
      const result = await callback(
        loadMigration,
        normalizeMigrationName(migration),
      );
      if (result === 'stop') break;
    }
  } catch (error) {
    Logger.error('❌ Migration failed:', error);
    throw error;
  }
};
/** Scaffolding templates are read from source — they are never part of dist output. */
const utilsPath = (fileName: string) => {
  return path.join(templatesDirectory, fileName);
};
const connectDb = async () => {
  const dbConfig = config().database;
  await initClient({
    client: dbConfig.client as DatabaseClient,
    host: dbConfig.host,
    port: dbConfig.port,
    username: dbConfig.username,
    password: dbConfig.password,
    database: dbConfig.database,
    settings: databaseCliConfig,
  });
};
export {
  handleMigration,
  createUpdatedAtTrigger,
  connectDb,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
  utilsPath,
};
