import { databaseCliConfig } from './config';
import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { Query } from '../../facades';
import { DatabaseClient } from '@repo/common-lib/types/database';
import Logger from '@repo/backend-lib/utils/console';
import { initClient } from '../../client';
import {config} from '@repo/common-lib/config';
import {
  createUpdatedAtTrigger,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
} from './triggers';

const handleMigration = async (
  callback: (migration: any, migrationName: string) => Promise<void>,
  rollback: boolean = false,
) => {
  try {
    const migrationDirectory = databaseCliConfig.migrationsDirectory;
    if (!fs.existsSync(migrationDirectory)) {
      fs.mkdirSync(migrationDirectory, { recursive: true });
    }
    // If rollback is true, we need to get the migrations from the database order by the last created at
    let migrations = !rollback
      ? fs.readdirSync(migrationDirectory)
      : (
          await Query.table('migrations')
            .select('name')
            .orderBy('created_at', 'DESC')
            .get()
        ).map((migration: any) => migration.name);

    if (migrations.length === 0) {
      Logger.info(
        `No migrations ${!rollback ? '' : 'to rollback'} found`,
      );
      // Important: don't hard-exit from here. Callers (e.g. db:fresh with
      // exitProcess: false) should decide whether the process should continue.
      return;
    }

    // Sort migrations alphabetically by filename. Files generated by
    // `create-migration.ts` use a zero-padded `YYYY-MM-DD-HH-mm-ss-ms-<slug>.ts`
    // prefix, so lexicographic ordering matches chronological ordering. Files
    // that don't fully follow the convention are simply sorted alphabetically
    // (no error is thrown).
    if (!rollback) {
      migrations = migrations
        .filter(
          (file) =>
            (file.endsWith('.js') || file.endsWith('.ts')) &&
            !file.endsWith('.d.ts'),
        )
        .sort((a: string, b: string) => a.localeCompare(b));
    }

    for (const migration of migrations) {
      const migrationPath = path.join(migrationDirectory, migration);
      if (!fs.existsSync(migrationPath)) {
        Logger.error('❌ Migration file not found', migrationPath);
        throw new Error(`Migration file not found: ${migrationPath}`);
      }
      const migrationFile = await import(pathToFileURL(migrationPath).href);
      if (!migrationFile.up || !migrationFile.down) {
        Logger.error(
          '❌ Migration file is not valid, missing up or down function',
          migrationPath,
        );
        throw new Error(`Invalid migration file (missing up/down): ${migrationPath}`);
      }
      await callback(migrationFile, migration);
    }
  } catch (error) {
    Logger.error('❌ Migration failed:', error);
    throw error;
  }
};
const utilsPath = (fileName: string) => {
  return path.join(process.cwd(), 'src', 'lib', 'scripts', 'utils', fileName);
};
const connectDb = async () => {
  const dbConfig = config().database;
  await initClient({
    client: dbConfig.client as DatabaseClient,
    host: dbConfig.host,
    port: dbConfig.port,
    username: dbConfig.username,
    password: dbConfig.password,
    database: dbConfig.database,
    settings: databaseCliConfig,
  });
};
export {
  handleMigration,
  createUpdatedAtTrigger,
  connectDb,
  createCreatedAtTrigger,
  createTimeStampsTrigger,
  utilsPath,
};
